CFLAGS=-std=c++0x
CC=g++


p31: c1.h p31-copy-move-const.cpp c1.cpp
	$(CC) p31-copy-move-const.cpp c1.cpp c1.h $(CFLAGS)

p31-1: c1.h p31-copy-move-const.cpp c1.cpp
	$(CC) p31-copy-move-assign.cpp c1.cpp c1.h $(CFLAGS)
